// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: modulestate.proto

package wire_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      *string                `protobuf:"bytes,1,opt,name=ModuleId,proto3,oneof" json:"ModuleId,omitempty"`
	ModuleName    *string                `protobuf:"bytes,2,opt,name=ModuleName,proto3,oneof" json:"ModuleName,omitempty"`
	ModuleVersion *string                `protobuf:"bytes,3,opt,name=ModuleVersion,proto3,oneof" json:"ModuleVersion,omitempty"`
	IsActive      *bool                  `protobuf:"varint,4,opt,name=IsActive,proto3,oneof" json:"IsActive,omitempty"`
	IsSolved      *bool                  `protobuf:"varint,5,opt,name=IsSolved,proto3,oneof" json:"IsSolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleState) Reset() {
	*x = ModuleState{}
	mi := &file_modulestate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleState) ProtoMessage() {}

func (x *ModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_modulestate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleState.ProtoReflect.Descriptor instead.
func (*ModuleState) Descriptor() ([]byte, []int) {
	return file_modulestate_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleState) GetModuleId() string {
	if x != nil && x.ModuleId != nil {
		return *x.ModuleId
	}
	return ""
}

func (x *ModuleState) GetModuleName() string {
	if x != nil && x.ModuleName != nil {
		return *x.ModuleName
	}
	return ""
}

func (x *ModuleState) GetModuleVersion() string {
	if x != nil && x.ModuleVersion != nil {
		return *x.ModuleVersion
	}
	return ""
}

func (x *ModuleState) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ModuleState) GetIsSolved() bool {
	if x != nil && x.IsSolved != nil {
		return *x.IsSolved
	}
	return false
}

var File_modulestate_proto protoreflect.FileDescriptor

const file_modulestate_proto_rawDesc = "" +
	"\n" +
	"\x11modulestate.proto\x12\n" +
	"wire_types\"\x88\x02\n" +
	"\vModuleState\x12\x1f\n" +
	"\bModuleId\x18\x01 \x01(\tH\x00R\bModuleId\x88\x01\x01\x12#\n" +
	"\n" +
	"ModuleName\x18\x02 \x01(\tH\x01R\n" +
	"ModuleName\x88\x01\x01\x12)\n" +
	"\rModuleVersion\x18\x03 \x01(\tH\x02R\rModuleVersion\x88\x01\x01\x12\x1f\n" +
	"\bIsActive\x18\x04 \x01(\bH\x03R\bIsActive\x88\x01\x01\x12\x1f\n" +
	"\bIsSolved\x18\x05 \x01(\bH\x04R\bIsSolved\x88\x01\x01B\v\n" +
	"\t_ModuleIdB\r\n" +
	"\v_ModuleNameB\x10\n" +
	"\x0e_ModuleVersionB\v\n" +
	"\t_IsActiveB\v\n" +
	"\t_IsSolvedB)Z'github.com/jax-b/ModulerKTNE/wire_typesb\x06proto3"

var (
	file_modulestate_proto_rawDescOnce sync.Once
	file_modulestate_proto_rawDescData []byte
)

func file_modulestate_proto_rawDescGZIP() []byte {
	file_modulestate_proto_rawDescOnce.Do(func() {
		file_modulestate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modulestate_proto_rawDesc), len(file_modulestate_proto_rawDesc)))
	})
	return file_modulestate_proto_rawDescData
}

var file_modulestate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modulestate_proto_goTypes = []any{
	(*ModuleState)(nil), // 0: wire_types.ModuleState
}
var file_modulestate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modulestate_proto_init() }
func file_modulestate_proto_init() {
	if File_modulestate_proto != nil {
		return
	}
	file_modulestate_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modulestate_proto_rawDesc), len(file_modulestate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modulestate_proto_goTypes,
		DependencyIndexes: file_modulestate_proto_depIdxs,
		MessageInfos:      file_modulestate_proto_msgTypes,
	}.Build()
	File_modulestate_proto = out.File
	file_modulestate_proto_goTypes = nil
	file_modulestate_proto_depIdxs = nil
}
