// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: wiremesage.proto

package wire_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_Set    Operation = 0
	Operation_Update Operation = 1
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "Set",
		1: "Update",
	}
	Operation_value = map[string]int32{
		"Set":    0,
		"Update": 1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_wiremesage_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_wiremesage_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_wiremesage_proto_rawDescGZIP(), []int{0}
}

type WireMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sender   uint32                 `protobuf:"varint,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver uint32                 `protobuf:"varint,2,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	Option   Operation              `protobuf:"varint,3,opt,name=Option,proto3,enum=wire_types.Operation" json:"Option,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*WireMessage_GameStateContent
	//	*WireMessage_ModuleStateContent
	Content       isWireMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireMessage) Reset() {
	*x = WireMessage{}
	mi := &file_wiremesage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireMessage) ProtoMessage() {}

func (x *WireMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wiremesage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireMessage.ProtoReflect.Descriptor instead.
func (*WireMessage) Descriptor() ([]byte, []int) {
	return file_wiremesage_proto_rawDescGZIP(), []int{0}
}

func (x *WireMessage) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *WireMessage) GetReceiver() uint32 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *WireMessage) GetOption() Operation {
	if x != nil {
		return x.Option
	}
	return Operation_Set
}

func (x *WireMessage) GetContent() isWireMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WireMessage) GetGameStateContent() *GameState {
	if x != nil {
		if x, ok := x.Content.(*WireMessage_GameStateContent); ok {
			return x.GameStateContent
		}
	}
	return nil
}

func (x *WireMessage) GetModuleStateContent() *ModuleState {
	if x != nil {
		if x, ok := x.Content.(*WireMessage_ModuleStateContent); ok {
			return x.ModuleStateContent
		}
	}
	return nil
}

type isWireMessage_Content interface {
	isWireMessage_Content()
}

type WireMessage_GameStateContent struct {
	GameStateContent *GameState `protobuf:"bytes,11,opt,name=GameStateContent,proto3,oneof"`
}

type WireMessage_ModuleStateContent struct {
	ModuleStateContent *ModuleState `protobuf:"bytes,12,opt,name=ModuleStateContent,proto3,oneof"`
}

func (*WireMessage_GameStateContent) isWireMessage_Content() {}

func (*WireMessage_ModuleStateContent) isWireMessage_Content() {}

var File_wiremesage_proto protoreflect.FileDescriptor

const file_wiremesage_proto_rawDesc = "" +
	"\n" +
	"\x10wiremesage.proto\x12\n" +
	"wire_types\x1a\x0fgamestate.proto\x1a\x11modulestate.proto\"\x8b\x02\n" +
	"\vWireMessage\x12\x16\n" +
	"\x06Sender\x18\x01 \x01(\rR\x06Sender\x12\x1a\n" +
	"\bReceiver\x18\x02 \x01(\rR\bReceiver\x12-\n" +
	"\x06Option\x18\x03 \x01(\x0e2\x15.wire_types.OperationR\x06Option\x12C\n" +
	"\x10GameStateContent\x18\v \x01(\v2\x15.wire_types.GameStateH\x00R\x10GameStateContent\x12I\n" +
	"\x12ModuleStateContent\x18\f \x01(\v2\x17.wire_types.ModuleStateH\x00R\x12ModuleStateContentB\t\n" +
	"\acontent* \n" +
	"\tOperation\x12\a\n" +
	"\x03Set\x10\x00\x12\n" +
	"\n" +
	"\x06Update\x10\x01B)Z'github.com/jax-b/ModulerKTNE/wire_typesb\x06proto3"

var (
	file_wiremesage_proto_rawDescOnce sync.Once
	file_wiremesage_proto_rawDescData []byte
)

func file_wiremesage_proto_rawDescGZIP() []byte {
	file_wiremesage_proto_rawDescOnce.Do(func() {
		file_wiremesage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wiremesage_proto_rawDesc), len(file_wiremesage_proto_rawDesc)))
	})
	return file_wiremesage_proto_rawDescData
}

var file_wiremesage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wiremesage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wiremesage_proto_goTypes = []any{
	(Operation)(0),      // 0: wire_types.Operation
	(*WireMessage)(nil), // 1: wire_types.WireMessage
	(*GameState)(nil),   // 2: wire_types.GameState
	(*ModuleState)(nil), // 3: wire_types.ModuleState
}
var file_wiremesage_proto_depIdxs = []int32{
	0, // 0: wire_types.WireMessage.Option:type_name -> wire_types.Operation
	2, // 1: wire_types.WireMessage.GameStateContent:type_name -> wire_types.GameState
	3, // 2: wire_types.WireMessage.ModuleStateContent:type_name -> wire_types.ModuleState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wiremesage_proto_init() }
func file_wiremesage_proto_init() {
	if File_wiremesage_proto != nil {
		return
	}
	file_gamestate_proto_init()
	file_modulestate_proto_init()
	file_wiremesage_proto_msgTypes[0].OneofWrappers = []any{
		(*WireMessage_GameStateContent)(nil),
		(*WireMessage_ModuleStateContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiremesage_proto_rawDesc), len(file_wiremesage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wiremesage_proto_goTypes,
		DependencyIndexes: file_wiremesage_proto_depIdxs,
		EnumInfos:         file_wiremesage_proto_enumTypes,
		MessageInfos:      file_wiremesage_proto_msgTypes,
	}.Build()
	File_wiremesage_proto = out.File
	file_wiremesage_proto_goTypes = nil
	file_wiremesage_proto_depIdxs = nil
}
